### ISSUE TITLE
Error compiling contracts

### ISSUE THREAD

**Issue by NodeGuy** [monax/cli#1337] opened 2017-04-14 04:52 UTC
Please include in your bug report:

- [ ] `docker version`

Docker version 17.03.0-ce, build 60ccb22

- [ ] `eris version`

Monax CLI Version: 0.16.0

- [ ] `docker-machine version` (if applicable / !linux)

docker-machine version 0.10.0, build 76ed2a6

- [ ] operating system details (osx/windows/linux)

Mac OS

- [ ] what you expected to happen

I expected that running a command from [the Getting Started tutorial](https://monax.io/docs/tutorials/getting-started/) should work:

```
$ monax pkgs do -z --chain simplechain --address $addr
```

- [ ] what actually happened

```
$ monax pkgs do --chain simplechain --address $addr

*****Executing Job*****

Job Name                                      defaultAddr

*****Executing Job*****

Job Name                                      setStorageBase

*****Executing Job*****

Job Name                                      deployStorageK
failed to send HTTP request Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
Error compiling contracts: Compilers error:
Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
```

- [ ] steps to reproduction

I followed the tutorial.

I tried the workaround suggested in the tutorial but it didn't work:

```
$ monax services start compilers
$ monax pkgs do --chain simplechain --address $addr --compiler 192.168.99.100:9091

*****Executing Job*****

Job Name                                      defaultAddr

*****Executing Job*****

Job Name                                      setStorageBase

*****Executing Job*****

Job Name                                      deployStorageK
failed to send HTTP request Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
Error compiling contracts: Compilers error:
Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
```

I tried the workaround in https://github.com/monax/cli/issues/1232 but it also didn't work:

```
$ monax pkgs do --chain simplechain --address $addr -z
Error: unknown shorthand flag: 'z' in -z
```

**Comment by VoR0220** [comment] 2017-04-14 05:40
@NodeGuy this is resolveable by going to the compilers.toml file and inputting 

ports = ["9099:9099"]

as the field.

**Comment by zramsay** [comment] 2017-04-14 12:30
should be fixed by #1338. The fix in #1232 no longer applies because between 0.12 and 0.16 the local compiler is used by default

**Comment by VoR0220** [comment] 2017-04-18 14:46
Closing as solved.

**Comment by NodeGuy** [comment] 2017-05-04 18:18
This workaround stopped working for me:

```
$ monax pkgs do --chain simplechain --address 021E292DCAF83F7D02DDEBC70044F23F74149ADF

*****Executing Job*****

Job Name                                      defaultAddr

*****Executing Job*****

Job Name                                      setStorageBase

*****Executing Job*****

Job Name                                      deployStorageK
failed to send HTTP request Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
Error compiling contracts: Compilers error:
Post http://127.0.0.1:9099: dial tcp 127.0.0.1:9099: getsockopt: connection refused
```

Here's my `compilers.toml` file:

```
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# These fields marshal roughly into the [docker run] command, see:
# https://docs.docker.com/engine/reference/run/

# For more information on configurations, see the services specification:
# https://monax.io/docs/documentation/cli/latest/services_specification/

name = "compilers"

description = """
Monax's Solidity Compiler Server.

This monax service compiles smart contract languages.
"""

status = "beta"

[service]
image = "quay.io/monax/compilers:0.16.0"
data_container = true
ports = ["9099:9099"]
user = ""
exec_host = ""
volumes = []

[maintainer]
name = "Monax Industries"
email = "support@monax.io"
```

**Comment by priteshpatel15** [comment] 2017-05-10 21:44
Im having this same issue.  Followed the tutorial and also added the ports 9099:9099

**Comment by priteshpatel15** [comment] 2017-05-10 21:58
How can I help to resolve this.

**Comment by priteshpatel15** [comment] 2017-05-10 21:59
I am on a Mac using Docker-Machine.  Followed the tutorial step by step.  Below is what my compilers file looks like:
`name = "compilers"

description = """
Monax's Solidity Compiler Server.

This monax service compiles smart contract languages.
"""

status = "beta"

[service]
image = "quay.io/monax/compilers:0.16.0"
data_container = true
ports = ["9099:9099"]
user = ""
exec_host = ""
volumes = []

[maintainer]
name = "Monax Industries"
email = "support@monax.io"`

**Comment by priteshpatel15** [comment] 2017-05-10 22:06
Ok.  Was a simple solution.  Thanks to 'Alex Tran Qui' in the slack chat ... I just needed the do a 'monax clean'.

After which I had to build the chain again but the compiler file stayed the same and that worked.

**Comment by zramsay** [comment] 2017-05-12 12:36
duplicate of #1360

**Closed by zramsay** 2017-05-12 12:36 UTC
