### ISSUE TITLE
Sporadic error `unexpected end of JSON input` after working with chain for a while

### ISSUE THREAD

**Issue by j-h-scheufen** [monax/cli#1045] opened 2016-10-23 21:54 UTC
Since upgrading to 0.12.0-rc3 the error `[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input` has been encountered a few times now when running EPM scripts. Stopping and restarting the chain resolves it. The error is sporadic and no reliable way to reproduce it is currently known.
This ticket merely records the problem as existing. Further information needs to be collected.

**Comment by rguikers** [comment] 2016-11-06 13:20
For me this is reproducible in 0.12 by setting wait:true in the deployment part of the epm.yml.
When setting wait:false i do not get the message

**Comment by zramsay** [comment] 2016-11-26 17:48
@j-h-scheufen has this issue persisted over the past month of bug fixes? @rguikers on the epm image 0.12.1 wait:true is default and cannot be over-riden: https://github.com/eris-ltd/eris-pm/pull/264

**Comment by zramsay** [comment] 2017-04-19 22:58
closing as resolved - this occured originally on 0.12.0-rc3 - we've come a long way since then

**Closed by zramsay** 2017-04-19 22:58 UTC
Labels: bug/unconfirmed, triaged, triaged/response needed
