### ISSUE TITLE
[chains] root node does not always connect to a chain

### ISSUE THREAD

**Issue by Akriti-sahu** [monax/cli#1186] opened 2017-01-27 05:59 UTC
hi @zramsay, thanks for your response. As I mentioned before in #1181 issue, I have created a chain in local systems with 1:full, 1:root and 2:validators . It was working fine. but due to some reason my one system that I have created as a root node, has been restarted (It means i didn't stop the chain manually by typing eris chains stop). then I again started my chain by using eris chains start command. It is showing that my chain is started as when I type eris chains ls, it is showing that my chain is active. But when I am checking this on my browser by typing http://localhost:46657/status where I can see the blocks are generating, it was not generating the blocks and when I am checking it by eris chains logs it was showing me logs like this-

INFO[01-24|04:35:44] SetHasVote(round-match) module=consensus peer="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" peerRound=0 height=9502 round=0 precommits=nil-BitArray index=1
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[NewRoundStep H:9502 R:0 S:RoundStepCommit LCR:0]"
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[CommitStep H:9502 BP:PartSet{T:1 6D7065F90B78} BA:BA{1:X}]"
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[NewRoundStep H:9503 R:0 S:RoundStepNewHeight LCR:0]"
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[HasVote VI:2 V:{9502/00/2} VI:2]"

but the other nodes that is 1 full and 2 validators were generating blocks properly. only this root node system which is been restarted was not generating the blocks.
Then due to this issue I have stopped my whole chain completely by typing eris chains stop and clean the eris by typing eris clean and then again started the chains first I started the 1:full node, then 1:root node and 2:validators node. and now my system is up.

So my question is that if due to some reason my root node system has been restarted and if I connect that node again to the chain it is no more creating any blocks, that means that root node is not working properly?? why it is so?? it should work properly after reconnect also as I thought but it was not.

Facing this issue as I restarted my whole chain in every node again (without doing **eris clean**) it generates few blocks (i.e. 13 blocks) then my root node again stop generating blocks.

**Comment by Akriti-sahu** [comment] 2017-01-31 08:13
Hi, @zramsay I don't know why my chain stops making blocks in root node. whenever I start this chain (that is having 1: full, 1: root and 2: validator nodes), after few hours it stops generating blocks.
For your information I have put the ip address of full node to the seed value of root and other 2 validator nodes. 
Then I again stop the chain at root node by typing 
` eris chains stop $chainName`
 and again started my chain then it is showing me logs like this

```
INFO[01-31|07:55:14] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[NewRoundStep H:26534 R:0 S:RoundStepPropose LCR:0]"
INFO[01-31|07:55:15] Server stop event fired. Good bye.       module=eris/server
INFO[01-31|07:55:21] Starting EventSwitch                     module=events impl=EventSwitch
NOTE[01-31|07:55:22] Loaded PrivValidator                     module=types file=/home/eris/.eris/chains/datachain/priv_validator.json privValidator="PrivValidator{5149874569DA23FB2F527C1EFC37B089B4369182 LH:0, LR:0, LS:0}"
Force disabling Tendermint's native RPC, which had been set to run on '0.0.0.0:46657' in the Tendermint config.
INFO[01-31|07:55:22] Starting EventSwitch                     module=events impl=EventSwitch
DBUG[01-31|07:55:22] addRound(round)                          module=consensus round=0
INFO[01-31|07:55:22] Local listener                           module=p2p ip=:: port=46656
INFO[01-31|07:55:22] Getting UPNP external address            module=p2p
INFO[01-31|07:55:25] Could not perform UPNP discover          module=p2p error="write udp4 0.0.0.0:60234->239.255.255.250:1900: i/o timeout"
INFO[01-31|07:55:25] Starting DefaultListener                 module=p2p impl=Listener(@172.17.0.3:46656)
NOTE[01-31|07:55:25] Added Listener(@172.17.0.3:46656)        module=node
INFO[01-31|07:55:25] Starting P2P Switch                      module=p2p impl="P2P Switch"
INFO[01-31|07:55:25] Starting BlockchainReactor               module=blockchain impl=BlockchainReactor
INFO[01-31|07:55:25] Starting ConsensusReactor                module=consensus impl=ConsensusReactor
NOTE[01-31|07:55:25] ConsensusReactor                         module=consensus fastSync=false
INFO[01-31|07:55:25] Starting ConsensusState                  module=consensus impl="ConsensusState(H:21548 R:0 S:RoundStepNewHeight"
NOTE[01-31|07:55:25] Catchup by replaying consensus messages  module=consensus n=8
NOTE[01-31|07:55:25] Vote                                     module=consensus height=21548 round=1 type=2 hash=4DFF2B987EB3D062CD6B0A6485470C0B970FF52B header="PartSet{T:1 D8D91DA33C59}" peer=20E3A6CE68D0D54F4E195840A11A450E1036220E813FB4D876A13E659270DD49
NOTE[01-31|07:55:25] Vote                                     module=consensus height=21548 round=1 type=2 hash=4DFF2B987EB3D062CD6B0A6485470C0B970FF52B header="PartSet{T:1 D8D91DA33C59}" peer=20E3A6CE68D0D54F4E195840A11A450E1036220E813FB4D876A13E659270DD49
NOTE[01-31|07:55:25] New Step                                 module=consensus height=21548 round=1 step=RoundStepPropose
NOTE[01-31|07:55:25] New Step                                 module=consensus height=21548 round=1 step=RoundStepPrecommit
NOTE[01-31|07:55:25] New Step                                 module=consensus height=21548 round=1 step=RoundStepCommit
NOTE[01-31|07:55:25] Timeout                                  module=consensus height=21548 round=1 step=RoundStepPropose dur=3.5s
INFO[01-31|07:55:25] Done catchup replay                      module=consensus
INFO[01-31|07:55:25] Starting MempoolReactor                  module=mempool impl=MempoolReactor
INFO[01-31|07:55:25] Server started.                          module=eris/server
WARN[01-31|07:55:25] WARNING (go-rpc): Please use fully formed listening addresses, including the tcp:// or unix:// prefix module=rpcserver
NOTE[01-31|07:55:25] Starting RPC HTTP server on tcp socket 0.0.0.0:46657 module=rpcserver
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /rpc                      --> github.com/eris-ltd/eris-db/rpc/v0.(*JsonRpcServer).(github.com/eris-ltd/eris-db/rpc/v0.handleFunc)-fm (5 handlers)
[GIN-debug] GET    /accounts                 --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleAccounts)-fm (6 handlers)
[GIN-debug] GET    /accounts/:address        --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleAccount)-fm (6 handlers)
[GIN-debug] GET    /accounts/:address/storage --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleStorage)-fm (6 handlers)
[GIN-debug] GET    /accounts/:address/storage/:key --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleStorageAt)-fm (7 handlers)
[GIN-debug] GET    /blockchain               --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleBlockchainInfo)-fm (5 handlers)
[GIN-debug] GET    /blockchain/chain_id      --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleChainId)-fm (5 handlers)
[GIN-debug] GET    /blockchain/genesis_hash  --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleGenesisHash)-fm (5 handlers)
[GIN-debug] GET    /blockchain/latest_block_height --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleLatestBlockHeight)-fm (5 handlers)
[GIN-debug] GET    /blockchain/latest_block  --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleLatestBlock)-fm (5 handlers)
[GIN-debug] GET    /blockchain/blocks        --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleBlocks)-fm (6 handlers)
[GIN-debug] GET    /blockchain/block/:height --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleBlock)-fm (6 handlers)
[GIN-debug] GET    /consensus                --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleConsensusState)-fm (5 handlers)
[GIN-debug] GET    /consensus/validators     --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleValidatorList)-fm (5 handlers)
[GIN-debug] POST   /event_subs               --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleEventSubscribe)-fm (5 handlers)
[GIN-debug] GET    /event_subs/:id           --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleEventPoll)-fm (5 handlers)
[GIN-debug] DELETE /event_subs/:id           --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleEventUnsubscribe)-fm (5 handlers)
[GIN-debug] GET    /namereg                  --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleNameRegEntries)-fm (6 handlers)
[GIN-debug] GET    /namereg/:key             --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleNameRegEntry)-fm (6 handlers)
[GIN-debug] GET    /network                  --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleNetworkInfo)-fm (5 handlers)
[GIN-debug] GET    /network/client_version   --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleClientVersion)-fm (5 handlers)
[GIN-debug] GET    /network/moniker          --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleMoniker)-fm (5 handlers)
[GIN-debug] GET    /network/listening        --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleListening)-fm (5 handlers)
[GIN-debug] GET    /network/listeners        --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleListeners)-fm (5 handlers)
[GIN-debug] GET    /network/peers            --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handlePeers)-fm (5 handlers)
[GIN-debug] GET    /network/peers/:address   --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handlePeer)-fm (6 handlers)
[GIN-debug] POST   /txpool                   --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleBroadcastTx)-fm (5 handlers)
[GIN-debug] GET    /txpool                   --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleUnconfirmedTxs)-fm (5 handlers)
[GIN-debug] POST   /calls                    --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleCall)-fm (5 handlers)
[GIN-debug] POST   /codecalls                --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleCallCode)-fm (5 handlers)
[GIN-debug] GET    /unsafe/pa_generator      --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleGenPrivAcc)-fm (5 handlers)
[GIN-debug] POST   /unsafe/txpool            --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleTransact)-fm (6 handlers)
[GIN-debug] POST   /unsafe/namereg/txpool    --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleTransactNameReg)-fm (5 handlers)
[GIN-debug] POST   /unsafe/tx_signer         --> github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleSignTx)-fm (5 handlers)
[GIN-debug] GET    /socketrpc                --> github.com/eris-ltd/eris-db/server.(*WebSocketServer).(github.com/eris-ltd/eris-db/server.handleFunc)-fm (5 handlers)
INFO[01-31|07:55:25] enterPrevote(21548/1). Current: 21548/0/RoundStepNewHeight module=consensus
WARN[01-31|07:55:25] enterPrevote: ProposalBlock is nil       module=consensus
INFO[01-31|07:55:25] Added to precommit                       module=consensus vote="Vote{21548/01/2(Precommit) 4DFF2B987EB3#PartSet{T:1 D8D91DA33C59} /368DBCB69348.../}" precommits="VoteSet{H:21548 R:1 T:2 +2/3:false BA{3:_X_}}"
INFO[01-31|07:55:25] Added to precommit                       module=consensus vote="Vote{21548/01/2(Precommit) 4DFF2B987EB3#PartSet{T:1 D8D91DA33C59} /E286B1132E7A.../}" precommits="VoteSet{H:21548 R:1 T:2 +2/3:true BA{3:_XX}}"
INFO[01-31|07:55:25] enterPrecommit(21548/1). Current: 21548/1/RoundStepPrevote module=consensus
INFO[01-31|07:55:25] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
INFO[01-31|07:55:25] enterCommit(21548/1). Current: 21548/1/RoundStepPrecommit module=consensus
WARN[01-31|07:55:25] Attempt to finalize failed. We don't have the commit block. module=consensus
INFO[01-31|07:57:06] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[HasVote VI:2 V:{26580/00/2} VI:2]"
INFO[01-31|07:57:06] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" peerRound=0 height=26580 round=0 precommits=nil-BitArray index=2
INFO[01-31|07:57:06] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[NewRoundStep H:26580 R:0 S:RoundStepCommit LCR:1]"
INFO[01-31|07:57:06] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[CommitStep H:26580 BP:PartSet{T:1 6C6B22A684F9} BA:BA{1:X}]"
INFO[01-31|07:57:06] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[NewRoundStep H:26581 R:0 S:RoundStepNewHeight LCR:0]"
INFO[01-31|07:57:07] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[NewRoundStep H:26581 R:0 S:RoundStepPropose LCR:0]"
INFO[01-31|07:57:07] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} 20E3A6CE68D0 out}" chId=20 msg="[HasVote VI:1 V:{26581/00/1} VI:1]"
```
Is anybody has any idea what I am doing wrong?? or why this is not working?? Please help.

**Comment by zramsay** [comment] 2017-02-06 12:09
hi @Akriti-sahu please provide a script to reproduce this error.

**Comment by Akriti-sahu** [comment] 2017-02-06 12:15
hi @zramsay, I am just simply creating a chain with 1:full, 1:root and 2:validators. The thing is that I daily used to stop this chain by using 
` eris chains stop $chainName `

and start daily using
`eris chains start $chainName`

It starts perfectly but after sometimes it stops making chain in my root node without doing anything.

**Comment by zramsay** [comment] 2017-02-06 15:41
are the 1 full and 2 Validators still moving the chain along? is it still making blocks? The chain should still make blocks even if the root node is not connected.

**Comment by Akriti-sahu** [comment] 2017-02-06 15:43
Yes....  Other nodes are still making blocks. Only root node has stopped.

On 06-Feb-2017 9:11 PM, "Zach" <notifications@github.com> wrote:

are the 1 full and 2 Validators still moving the chain along? is it still
making blocks? The chain should still make blocks even if the root node is
not connected.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/eris-ltd/eris/issues/1186#issuecomment-277720436>, or mute
the thread

**Comment by Akriti-sahu** [comment] 2017-02-06 15:49
And the root node is not disconnected it is still connected but not creating any blocks.

**Comment by zramsay** [comment] 2017-02-06 15:51
Ok, this looks similar to #1185 and related logs/docker issues which are being worked on. It will take some time to reproduce & debug.

**Comment by zramsay** [comment] 2017-04-19 20:36
closing since this is really a tendermint issue

**Closed by zramsay** 2017-04-19 20:36 UTC
Labels: bug/unconfirmed, triaged
