### ISSUE TITLE
Smart contract deploying problem

### ISSUE THREAD

**Issue by test2015deve** [monax/cli#1356] opened 2017-04-20 12:35 UTC
Hi,

I had a problem while deploying the my smart contract. Do you have any idea about what is the problem? Thank you very much

Command : monax pkgs do --chain testchain --address $addr 

Error : _Error connnecting to node (tcp://172.17.0.3:46657) to query contract at (40A7F04C0400389A540C2DC2B29199FB418DC016) with data (6D4CE63C)%!(EXTRA string=Response error: Error unreflecting result: Account 40a7f04c0400389a540c2dc2b29199fb418dc016 does not exist)_

**Comment by zramsay** [comment] 2017-04-20 12:39
I assume this worked fine on `0.12.0` ? Can you provide reproduction steps (including how you made the chain, the `epm.yaml` and the contracts you're deploying)?

**Comment by test2015deve** [comment] 2017-04-20 12:48
Hi,

Here is the basic commands ı used.


**monax chains make --account-types=Root:1,Full:2 testchain

chain_dir=$HOME/.monax/chains/testchain
chain_dir_this=$chain_dir/testchain_full_000
addr=$(cat $chain_dir/addresses.csv | grep testchain_full_000 | cut -d ',' -f 1)
monax chains start testchain --init-dir $chain_dir_this  
monax chains logs testchain**

And I created a sol.file.

and the copy paste epm.yaml from the your website:
jobs:

- name: setStorageBase
  job:
    set:
      val: 5

- name: deployStorageK
  job:
    deploy:
      contract: idi.sol

- name: setStorage
  job:
    call:
      destination: $deployStorageK
      data: set $setStorageBase

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      data: get

- name: assertStorage
  job:
    assert:
      key: $queryStorage
      relation: eq
      val: $setStorageBase
----------------------------------------------------------------------------------------------------------------

And the last command is: **monax pkgs do --chain testchain --address $addr** 

and ı get the error

**Comment by test2015deve** [comment] 2017-04-20 12:50
Yes , it was worked fine on 0.12.0. But not works fine on 0.16.0

**Comment by zramsay** [comment] 2017-04-20 13:06
Ok, it looks like a bug, thanks for uncovering it. In the meantime, there are ~40 examples here https://github.com/monax/cli/tree/master/tests/jobs_fixtures ... these are included as part of the test sequence so they should work for you

**Comment by silasdavis** [comment] 2017-04-20 13:21
This issue does not occur with a chain-type of `simplechain` which has a single 'full' account. To reproduce you need to build a testchain as given.

**Comment by zramsay** [comment] 2017-04-20 13:31
@test2015deve the `monax chains make --account-types=Root:1,Full:2 testchain` created two Full accounts, which are validators and you'd thus need to create a multi-node chain (see [this tutorial](https://monax.io/docs/chain-deploying/)) for more information. I see also that running `monax chains logs testchain` produced no output, suggesting you chain is not running.

**Comment by zramsay** [comment] 2017-04-20 13:38
can you try making a chain with `monax chains make singlechain` and confirming that `monax pkgs do` works

**Comment by silasdavis** [comment] 2017-04-20 13:40
Just to give a little explanation of the slightly unhelpful error message. The rpc layer is misdirecting us with the `error unreflecting result` text. The issue is really that the Account cannot be found because we are querying an uninitialised chain state because no blocks have been produced, which cannot happen without a quorum of validators (>= 2/3 total), in this case being 2.

**Comment by test2015deve** [comment] 2017-04-24 06:19
Hi,

When ı set up blockchain with the 1 node. There is no problem. Now ı am getting another problems with new version which is not related this issue. After they are solved, Im gonna try to set up blockchain with more nodes

Thanks for your help

**Comment by zramsay** [comment] 2017-04-24 16:37
> there is no problem
...
> another problems ... not related [to] this issue

closing per the above comments

**Closed by zramsay** 2017-04-24 16:37 UTC
Labels: bug/confirmed
