### ISSUE TITLE
Not able to instantiate the Blockchain: I'm following tutorial

### ISSUE THREAD

**Issue by vikas1188** [monax/cli#1154] opened 2016-12-28 12:07 UTC
Please include in your bug report:

- [x] `docker version`
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 02:47:26 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/version: open //./pipe/docker_engine: The system cannot find the file speci
fied.

- [x] `eris version`
$ eris_0.12.0_windows_amd64.exe version
Eris CLI Version: 0.12.0 (002c63e)

- [ ] `go version` (if applicable)

- [x] `docker-machine version` (if applicable / !linux)
docker-machine version 0.8.2, build e18a919
- [x] operating system details (osx/windows/linux)
Window 8.1 pro
- [x] what you expected to happen
it should have started the new Blockchain. but it didn't.
- [x] what actually happened
I try to start the chain using the command:

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains new simplechain --dir $chain_dir_this**
Command "new" is deprecated, it has been replaced by [eris chains start NAME --i
nit-dir]

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains ls**
CHAIN           ON     CONTAINER ID     DATA CONTAINER
simplechain     -      26895e4596       faa8dbd955

even after changing to the command, as per the above feedback in bold from eris was not helping.

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains start simplechain --init-dir $chain_dir_
this**

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains ls**
CHAIN           ON     CONTAINER ID     DATA CONTAINER
simplechain     -      26895e4596       faa8dbd955

it’s not started. then I checked the logs.

Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains logs simplechain
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml

then I found that it is trying to find the files in the "**/home/eris/.eris/chains/simplechain**" directory on windows. Ideally it should find the file inside **/c/Users/Vikas/.eris/chains/simplechain/** .putting the logs below as it is. 

**Vikas@Vikas-PC **MINGW64** /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains logs simplechain**
Fatal error reading configuration
                                    directory=**/home/eris/**.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
- [x] steps to reproduction

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ echo $HOME**
/c/Users/Vikas

set the variable in doker quickstart terminal as per the document like below:
**chain_dir=$HOME/.eris/chains/simplechain**
**chain_dir_this=$chain_dir/simplechain_full_000**

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ echo $chain_dir**
/c/Users/Vikas/.eris/chains/simplechain

**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ echo $chain_dir_this**
/c/Users/Vikas/.eris/chains/simplechain/simplechain_full_000

**document link:** 
https://monax.io/docs/tutorials/getting-started/
**Section:**
Step 2.a.2. Make the genesis.json

Kindly consider that i've completed all the previous steps as mentioned.
Now, you try to start the blockchain using the command:

**$ eris chains new simplechain --dir $chain_dir_this**

**$ eris_0.12.0_windows_amd64.exe chains ls**
CHAIN           ON     CONTAINER ID     DATA CONTAINER
simplechain     -      26895e4596       faa8dbd955

**$ eris_0.12.0_windows_amd64.exe chains logs simplechain**
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml

If I'm missing anything, kindly let me know. 

If issue is a feature request, tell us why this feature is useful.

**Comment by pietv** [comment] 2016-12-28 12:27
hi @vikas1188, thank you reporting an issue and that you've found a tutorial glitch that needs correcting (the deprecated `new` command: we're using `eris chains start` command instead).

> then I found that it is trying to find the files in the "/home/eris/.eris/chains/simplechain" directory on windows. Ideally it should find the file inside /c/Users/Vikas/.eris/chains/simplechain/ .putting the logs below as it is.
This is actually correct, because those log lines are from inside the container which runs Linux (the chain data from your Windows host machine is being generated / copied inside that container).

Please, could you try to create your chain again with the `eris chains start --init-dir $chain_dir_this` instead of `eris chains new` by running the recipe again (`eris clean` then `eris make` then `eris start` to see if it's running this time). Thanks!

I'll try to repeat the tutorial to see if I see the bug. Will get back to you.

**Comment by pietv** [comment] 2016-12-28 12:33
Could please also attach the debug log of the `eris chains start` command by running it with the `-d` flag, if the chain still isn't started. Thanks.

**Comment by vikas1188** [comment] 2016-12-28 12:52
here you go:


**Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains start -d simplechain --init-dir $chain_dir_this**
Getting connection details from environment
                                    cert path=C:\Users\Vikas\.docker\machine\machines\default
                                         host=tcp://192.168.99.100:2376
Getting connection details from Docker Machine
                                      machine=eris
                                    cert path=C:\Users\Vikas\.docker\machine\machines\default
                                         host=tcp://192.168.99.100:2376
Connecting to Docker via TLS        cert path=C:\Users\Vikas\.docker\machine\machines\default
                                         host=tcp://192.168.99.100:2376
Connected via TLS
Successfully connected to Docker daemon
Setting ERIS_IPFS_HOST                    url=http://192.168.99.100
Chain definition loaded            chain name=simplechain
                                          cmd=
                                   entrypoint=
                                  environment=[]
Booting chain dependencies             chains=[]
                                     services=[]
Starting a chain                              simplechain
                              chain container=simplechain-8e40d46a-38f2-442e-8419-6b60f077f027
                                  environment=[]
                              ports published=false
Running container                             simplechain-8e40d46a-38f2-442e-8419-6b60f077f027
Manage data containers?              autodata=true
Data container already exists. Not creating
Container already exists. Not creating
Starting container                            simplechain-8e40d46a-38f2-442e-8419-6b60f077f027
                                          cmd=[]
                               data container=simplechain-cc22a990-066f-4bea-b66e-cdb0fa12bd54
                                   entrypoint=[]
                                  environment=[]
                                        image=quay.io/eris/db:0.12.0
                              published ports=false
Container started                             simplechain-8e40d46a-38f2-442e-8419-6b60f077f027

Vikas@Vikas-PC MINGW64 /c/Program Files/Docker Toolbox
$ eris_0.12.0_windows_amd64.exe chains ls
CHAIN           ON     CONTAINER ID     DATA CONTAINER
simplechain     -      85e7e41cc7       a3da1307d9


P.S. Can you confirm the command I'm using to instantiate the blockchain is correct or not ? As this is not the one, which is in the document. 
document has the **"new"** & I'm using the **"start"** one.

**Comment by pietv** [comment] 2016-12-28 12:54
@vikas1188 thank you for the log. I was able to reproduce it on Windows 10 as well, so this is a bug.

The correct command is `start`, but you should be able to use `new` as well.

**Comment by vikas1188** [comment] 2016-12-28 17:07
Hey pietv. I'm trying to use MONAX (formerly ERIS) in blockchain-govhack. So it would be great if you can let me know the tentative timeline of fixing this bug.
Meanwhile, I shall check other frameworks. As I've heard so much about it, all good words, I started with it, but hit a roadblock. 
So share the time line if you can please. Kinda urgent. 
Peace!

**Comment by hejnal** [comment] 2017-01-25 00:06
Hi,

I´m experiencing the very same problem.

`$ eris chains logs simplechain
Fatal error reading configuration
                                    directory=/home/eris/.eris/chains/simplechain
                                         file=config.toml`

I would be grateful if you could advise about this bugfix. Is it only related to the tutorial?

Thanks in advance!

**Comment by zramsay** [comment] 2017-01-25 18:41
@hejnal can you describe the exact steps you too to create and start the chain?

**Comment by zramsay** [comment] 2017-04-11 22:54
closing as unresponsive. pleas re-open if same problem is encountered in v0.16.0

**Closed by zramsay** 2017-04-11 22:54 UTC
Labels: area/test suite, bug/critical, triaged
