### ISSUE TITLE
[monax install] implement new feature

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1017] opened 2016-10-13 02:35 UTC
@VoR0220 commented on [Thu May 12 2016](https://github.com/eris-ltd/eris-pm/issues/121)

In order to create a "bundle"/"package", there should be a command that creates the epm.yaml file, a CMC (contract managing contract), and a readme.md inside of the current working directory.

**Comment by zramsay** [comment] 2017-04-20 00:54
duplicate of #1018

**Closed by zramsay** 2017-04-20 00:54 UTC
Labels: area/libraries, area/pm, triaged, type/enhancement
