### ISSUE TITLE
[Data] When machines aren't properly connected data import goes into infinite loop

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1115] opened 2016-11-30 22:44 UTC
**Problem** -- when a "host" machine cannot fully connect to the docker engine on a "remote" (virtualbox or otherwise) the data import in data/data.goL144,178 goes into a loop.

**Solution** -- cap the recursion.

Additional debugging information kindly provided by @ratranqu . 

```
In my case, I had the machine from which I was driving things (the one on which 
I did `eris make …` in a Digital Ocean group, and I was creating my eris nodes 
(validators and all) in a different Digital Ocean group. I suspect that this prevented 
the install process from copying the chain directory to the nodes and thus the 
recursive call to create the data directory threw (probably good to prevent infinite 
depth in the recursion at data.go:144 and data.go:178 by allowing a single level of 
recursion).
```

It's unclear to me if this is related to #962 or not. If it is redundant then the debugging information provided here should be moved to that issue.

**Comment by zramsay** [comment] 2016-12-01 20:37
definitely a duplicate of #962. Replacing with this issue

**Comment by zramsay** [comment] 2017-04-18 16:44
cli should no longer be used in the in the way that led to this issue; also unwinding use of data containers

**Closed by zramsay** 2017-04-18 16:44 UTC
Labels: area/docker, bug/confirmed, triaged
